events { worker_connections 1024; }

http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;
  sendfile      on;
  server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;

    # Angular SPA
    location / {
      try_files $uri $uri/ /index.html;
    }

        # Serve config.json file
        location /assets/config/config.json {
            try_files $uri =404;
        }
  }
}
